# Generated by Django 5.0.1 on 2024-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlesson',
            options={'verbose_name': 'Text Lesson', 'verbose_name_plural': 'Text Lessons'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name': 'Video Lesson', 'verbose_name_plural': 'Video Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textlesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='textlesson',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='slug',
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='defult', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
