# Generated by Django 5.0.1 on 2024-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_textlesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlesson',
            name='view_time',
            field=models.PositiveIntegerField(default=0, verbose_name='View time in minutes'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='view_time',
            field=models.PositiveIntegerField(default=0, verbose_name='View time in minutes'),
        ),
    ]
