# Generated by Django 5.0.1 on 2024-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_temporaryuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='full_name',
            field=models.CharField(default='rex burby', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
