# Generated by Django 5.0.1 on 2024-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_temporaryuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='John Smith', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
