# Generated by Django 5.0.1 on 2024-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='temporaryuser',
            name='users_tempo_email_9e1cd9_idx',
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AddIndex(
            model_name='temporaryuser',
            index=models.Index(fields=['email', 'session', 'verification_code', 'created'], name='users_tempo_email_19a83d_idx'),
        ),
    ]
